spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/user/OneDrive/Bureau/SDIA/Distribued-Systems/Micro-Services-Consul/config-repo
          default-label: master

server:
  port: 8888

